test:
  image: node:alpine
  script:
    - apk add --no-cache curl
    - curl -L https://unpkg.com/@pnpm/self-installer | node
    - pnpm install
    - pnpm run check
  stage: test

pages:
  image: ruby:alpine
  script:
    - bundle config set path 'vendor/'
    - bundle install
    - bundle exec jekyll build -s pages/ -d public/
  stage: deploy
  rules:
    - changes:
        - pages/*
      when: always
  cache:
    paths:
      - vendor/
  artifacts:
    paths:
      - public/
